/*   Copyright 2004 Jacob Eggleston
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *   ========================================================================
 *
 *   User: Jacob Eggleston
 *   Date: 2005/7/29
 */

using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

using Ch3Etah.Core.Metadata;
using Ch3Etah.Core.ProjectLib;
using Ch3Etah.Metadata.OREntities;

namespace Ch3Etah.Gui.DocumentHandling {

	public class OREntityFieldEditor : System.Windows.Forms.UserControl, IObjectEditor {
			
		private EntityField _field;

		#region Windows Form Designer generated code


		/// <summary>
		/// Required designer variable.
		/// </summary>
		private Container components = null;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.TextBox txtName;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.TextBox txtDBName;
		private System.Windows.Forms.CheckBox chkHidden;
		private System.Windows.Forms.TextBox txtDefaultValue;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.TextBox txtNullValue;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.CheckBox chkAllowNull;
		private System.Windows.Forms.CheckBox chkSerialize;
		private System.Windows.Forms.CheckBox chkExclude;
		private System.Windows.Forms.CheckBox chkReadOnly;
		private System.Windows.Forms.CheckBox chkKeyField;
		private System.Windows.Forms.CheckBox chkAutogenerated;
		private System.Windows.Forms.GroupBox groupBox2;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.Label label9;
		private System.Windows.Forms.CheckBox chkIdentity;
		private System.Windows.Forms.CheckBox chkDBReadOnly;
		private System.Windows.Forms.TextBox txtDBType;
		private System.Windows.Forms.TextBox txtVBType;
		private System.Windows.Forms.TextBox txtType;
		private System.Windows.Forms.TextBox txtDBPrecision;
		private System.Windows.Forms.TextBox txtDBSize;
		private System.Windows.Forms.ErrorProvider errorProvider;

		public OREntityFieldEditor(EntityField field) : this() {
			_field = field;
		}

		public OREntityFieldEditor() {
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			this.Enabled = false;
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose(bool disposing) {
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}


		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent() {
			this.errorProvider = new System.Windows.Forms.ErrorProvider();
			this.txtDBName = new System.Windows.Forms.TextBox();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.chkDBReadOnly = new System.Windows.Forms.CheckBox();
			this.chkAutogenerated = new System.Windows.Forms.CheckBox();
			this.chkExclude = new System.Windows.Forms.CheckBox();
			this.chkReadOnly = new System.Windows.Forms.CheckBox();
			this.chkIdentity = new System.Windows.Forms.CheckBox();
			this.chkHidden = new System.Windows.Forms.CheckBox();
			this.chkSerialize = new System.Windows.Forms.CheckBox();
			this.chkKeyField = new System.Windows.Forms.CheckBox();
			this.txtName = new System.Windows.Forms.TextBox();
			this.label6 = new System.Windows.Forms.Label();
			this.label1 = new System.Windows.Forms.Label();
			this.txtDefaultValue = new System.Windows.Forms.TextBox();
			this.label2 = new System.Windows.Forms.Label();
			this.txtNullValue = new System.Windows.Forms.TextBox();
			this.label3 = new System.Windows.Forms.Label();
			this.chkAllowNull = new System.Windows.Forms.CheckBox();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this.txtDBPrecision = new System.Windows.Forms.TextBox();
			this.txtDBSize = new System.Windows.Forms.TextBox();
			this.label8 = new System.Windows.Forms.Label();
			this.label9 = new System.Windows.Forms.Label();
			this.txtDBType = new System.Windows.Forms.TextBox();
			this.label4 = new System.Windows.Forms.Label();
			this.txtVBType = new System.Windows.Forms.TextBox();
			this.txtType = new System.Windows.Forms.TextBox();
			this.label5 = new System.Windows.Forms.Label();
			this.label7 = new System.Windows.Forms.Label();
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.SuspendLayout();
			// 
			// errorProvider
			// 
			this.errorProvider.ContainerControl = this;
			// 
			// txtDBName
			// 
			this.txtDBName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.txtDBName.Enabled = false;
			this.txtDBName.Location = new System.Drawing.Point(304, 8);
			this.txtDBName.Name = "txtDBName";
			this.txtDBName.Size = new System.Drawing.Size(196, 21);
			this.txtDBName.TabIndex = 3;
			this.txtDBName.Text = "textBox1";
			// 
			// groupBox1
			// 
			this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox1.Controls.Add(this.chkDBReadOnly);
			this.groupBox1.Controls.Add(this.chkAutogenerated);
			this.groupBox1.Controls.Add(this.chkExclude);
			this.groupBox1.Controls.Add(this.chkReadOnly);
			this.groupBox1.Controls.Add(this.chkIdentity);
			this.groupBox1.Controls.Add(this.chkHidden);
			this.groupBox1.Controls.Add(this.chkSerialize);
			this.groupBox1.Controls.Add(this.chkKeyField);
			this.groupBox1.Location = new System.Drawing.Point(4, 96);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(496, 64);
			this.groupBox1.TabIndex = 9;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Attributes";
			// 
			// chkDBReadOnly
			// 
			this.chkDBReadOnly.Enabled = false;
			this.chkDBReadOnly.Location = new System.Drawing.Point(272, 36);
			this.chkDBReadOnly.Name = "chkDBReadOnly";
			this.chkDBReadOnly.Size = new System.Drawing.Size(132, 24);
			this.chkDBReadOnly.TabIndex = 7;
			this.chkDBReadOnly.Text = "Read-Only in DB";
			// 
			// chkAutogenerated
			// 
			this.chkAutogenerated.Location = new System.Drawing.Point(172, 36);
			this.chkAutogenerated.Name = "chkAutogenerated";
			this.chkAutogenerated.TabIndex = 6;
			this.chkAutogenerated.Text = "Autogenerate";
			// 
			// chkExclude
			// 
			this.chkExclude.Location = new System.Drawing.Point(92, 36);
			this.chkExclude.Name = "chkExclude";
			this.chkExclude.TabIndex = 5;
			this.chkExclude.Text = "Exclude";
			// 
			// chkReadOnly
			// 
			this.chkReadOnly.Location = new System.Drawing.Point(272, 16);
			this.chkReadOnly.Name = "chkReadOnly";
			this.chkReadOnly.TabIndex = 3;
			this.chkReadOnly.Text = "Read-Only";
			// 
			// chkIdentity
			// 
			this.chkIdentity.Enabled = false;
			this.chkIdentity.Location = new System.Drawing.Point(172, 16);
			this.chkIdentity.Name = "chkIdentity";
			this.chkIdentity.TabIndex = 2;
			this.chkIdentity.Text = "Identity";
			// 
			// chkHidden
			// 
			this.chkHidden.Location = new System.Drawing.Point(92, 16);
			this.chkHidden.Name = "chkHidden";
			this.chkHidden.TabIndex = 1;
			this.chkHidden.Text = "Hidden";
			// 
			// chkSerialize
			// 
			this.chkSerialize.Location = new System.Drawing.Point(12, 36);
			this.chkSerialize.Name = "chkSerialize";
			this.chkSerialize.TabIndex = 4;
			this.chkSerialize.Text = "Serialize";
			// 
			// chkKeyField
			// 
			this.chkKeyField.Enabled = false;
			this.chkKeyField.Location = new System.Drawing.Point(12, 16);
			this.chkKeyField.Name = "chkKeyField";
			this.chkKeyField.TabIndex = 0;
			this.chkKeyField.Text = "Key Field";
			// 
			// txtName
			// 
			this.txtName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.txtName.Location = new System.Drawing.Point(76, 8);
			this.txtName.Name = "txtName";
			this.txtName.Size = new System.Drawing.Size(132, 21);
			this.txtName.TabIndex = 1;
			this.txtName.Text = "textBox6";
			// 
			// label6
			// 
			this.label6.Location = new System.Drawing.Point(4, 12);
			this.label6.Name = "label6";
			this.label6.Size = new System.Drawing.Size(100, 16);
			this.label6.TabIndex = 0;
			this.label6.Text = "Link Name";
			// 
			// label1
			// 
			this.label1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.label1.Location = new System.Drawing.Point(216, 12);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(120, 16);
			this.label1.TabIndex = 2;
			this.label1.Text = "Field Name in DB ";
			// 
			// txtDefaultValue
			// 
			this.txtDefaultValue.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.txtDefaultValue.Location = new System.Drawing.Point(76, 36);
			this.txtDefaultValue.Name = "txtDefaultValue";
			this.txtDefaultValue.Size = new System.Drawing.Size(132, 21);
			this.txtDefaultValue.TabIndex = 5;
			this.txtDefaultValue.Text = "textBox6";
			// 
			// label2
			// 
			this.label2.Location = new System.Drawing.Point(4, 40);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(100, 16);
			this.label2.TabIndex = 4;
			this.label2.Text = "Default Value";
			// 
			// txtNullValue
			// 
			this.txtNullValue.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.txtNullValue.Location = new System.Drawing.Point(76, 64);
			this.txtNullValue.Name = "txtNullValue";
			this.txtNullValue.Size = new System.Drawing.Size(132, 21);
			this.txtNullValue.TabIndex = 7;
			this.txtNullValue.Text = "textBox6";
			// 
			// label3
			// 
			this.label3.Location = new System.Drawing.Point(4, 68);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(100, 16);
			this.label3.TabIndex = 6;
			this.label3.Text = "Null Value";
			// 
			// chkAllowNull
			// 
			this.chkAllowNull.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.chkAllowNull.Location = new System.Drawing.Point(216, 68);
			this.chkAllowNull.Name = "chkAllowNull";
			this.chkAllowNull.Size = new System.Drawing.Size(116, 16);
			this.chkAllowNull.TabIndex = 8;
			this.chkAllowNull.Text = "Allow Nulls";
			// 
			// groupBox2
			// 
			this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
				| System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox2.Controls.Add(this.txtDBPrecision);
			this.groupBox2.Controls.Add(this.txtDBSize);
			this.groupBox2.Controls.Add(this.label8);
			this.groupBox2.Controls.Add(this.label9);
			this.groupBox2.Controls.Add(this.txtDBType);
			this.groupBox2.Controls.Add(this.label4);
			this.groupBox2.Controls.Add(this.txtVBType);
			this.groupBox2.Controls.Add(this.txtType);
			this.groupBox2.Controls.Add(this.label5);
			this.groupBox2.Controls.Add(this.label7);
			this.groupBox2.Location = new System.Drawing.Point(4, 168);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(496, 160);
			this.groupBox2.TabIndex = 10;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Additional Information";
			// 
			// txtDBPrecision
			// 
			this.txtDBPrecision.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.txtDBPrecision.Enabled = false;
			this.txtDBPrecision.Location = new System.Drawing.Point(300, 76);
			this.txtDBPrecision.Name = "txtDBPrecision";
			this.txtDBPrecision.Size = new System.Drawing.Size(188, 21);
			this.txtDBPrecision.TabIndex = 9;
			this.txtDBPrecision.Text = "textBox1";
			// 
			// txtDBSize
			// 
			this.txtDBSize.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.txtDBSize.Enabled = false;
			this.txtDBSize.Location = new System.Drawing.Point(72, 77);
			this.txtDBSize.Name = "txtDBSize";
			this.txtDBSize.Size = new System.Drawing.Size(148, 21);
			this.txtDBSize.TabIndex = 7;
			this.txtDBSize.Text = "textBox6";
			// 
			// label8
			// 
			this.label8.Location = new System.Drawing.Point(8, 80);
			this.label8.Name = "label8";
			this.label8.Size = new System.Drawing.Size(100, 16);
			this.label8.TabIndex = 6;
			this.label8.Text = "DB Size";
			// 
			// label9
			// 
			this.label9.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.label9.Location = new System.Drawing.Point(232, 81);
			this.label9.Name = "label9";
			this.label9.Size = new System.Drawing.Size(120, 16);
			this.label9.TabIndex = 8;
			this.label9.Text = "DB Precision";
			// 
			// txtDBType
			// 
			this.txtDBType.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.txtDBType.Enabled = false;
			this.txtDBType.Location = new System.Drawing.Point(72, 49);
			this.txtDBType.Name = "txtDBType";
			this.txtDBType.Size = new System.Drawing.Size(148, 21);
			this.txtDBType.TabIndex = 5;
			this.txtDBType.Text = "textBox6";
			// 
			// label4
			// 
			this.label4.Location = new System.Drawing.Point(8, 52);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(100, 16);
			this.label4.TabIndex = 4;
			this.label4.Text = "DB Type";
			// 
			// txtVBType
			// 
			this.txtVBType.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.txtVBType.Location = new System.Drawing.Point(300, 21);
			this.txtVBType.Name = "txtVBType";
			this.txtVBType.Size = new System.Drawing.Size(188, 21);
			this.txtVBType.TabIndex = 3;
			this.txtVBType.Text = "textBox1";
			// 
			// txtType
			// 
			this.txtType.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right)));
			this.txtType.Enabled = false;
			this.txtType.Location = new System.Drawing.Point(72, 21);
			this.txtType.Name = "txtType";
			this.txtType.Size = new System.Drawing.Size(148, 21);
			this.txtType.TabIndex = 1;
			this.txtType.Text = "textBox6";
			// 
			// label5
			// 
			this.label5.Location = new System.Drawing.Point(8, 24);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(100, 16);
			this.label5.TabIndex = 0;
			this.label5.Text = ".NET Type";
			// 
			// label7
			// 
			this.label7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.label7.Location = new System.Drawing.Point(232, 25);
			this.label7.Name = "label7";
			this.label7.Size = new System.Drawing.Size(120, 16);
			this.label7.TabIndex = 2;
			this.label7.Text = "VB Type";
			// 
			// OREntityFieldEditor
			// 
			this.Controls.Add(this.groupBox2);
			this.Controls.Add(this.chkAllowNull);
			this.Controls.Add(this.txtNullValue);
			this.Controls.Add(this.label3);
			this.Controls.Add(this.txtDefaultValue);
			this.Controls.Add(this.label2);
			this.Controls.Add(this.txtDBName);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.txtName);
			this.Controls.Add(this.label6);
			this.Controls.Add(this.label1);
			this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.Name = "OREntityFieldEditor";
			this.Size = new System.Drawing.Size(504, 332);
			this.Load += new System.EventHandler(this.ORIndexEditor_Load);
			this.groupBox1.ResumeLayout(false);
			this.groupBox2.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion

		#region IObjectEditor implementation
		
		public event EventHandler SelectedObjectChanged;
		protected virtual void OnSelectedObjectChanged() {
			if (this.SelectedObjectChanged != null) {
				SelectedObjectChanged(this.SelectedObject, new EventArgs());
			}
		}

		#region DoBinding
		private void DoBinding() {
			txtName.DataBindings.Clear();
			txtDBName.DataBindings.Clear();
			txtDefaultValue.DataBindings.Clear();
			txtNullValue.DataBindings.Clear();
			chkAllowNull.DataBindings.Clear();
			chkKeyField.DataBindings.Clear();
			chkHidden.DataBindings.Clear();
			chkIdentity.DataBindings.Clear();
			chkReadOnly.DataBindings.Clear();
			chkSerialize.DataBindings.Clear();
			chkExclude.DataBindings.Clear();
			chkAutogenerated.DataBindings.Clear();
			chkDBReadOnly.DataBindings.Clear();
			txtType.DataBindings.Clear();
			txtVBType.DataBindings.Clear();
			txtDBType.DataBindings.Clear();
			txtDBSize.DataBindings.Clear();
			txtDBPrecision.DataBindings.Clear();

			txtName.DataBindings.Add("Text", _field, "Name");
			txtDBName.DataBindings.Add("Text", _field, "DBColumn");
			txtDefaultValue.DataBindings.Add("Text", _field, "DefaultValue");
			txtNullValue.DataBindings.Add("Text", _field, "NullValue");
			chkAllowNull.DataBindings.Add("Checked", _field, "AllowNull");
			chkKeyField.DataBindings.Add("Checked", _field, "KeyField");
			chkHidden.DataBindings.Add("Checked", _field, "Hidden");
			chkIdentity.DataBindings.Add("Checked", _field, "DBIdentity");
			chkReadOnly.DataBindings.Add("Checked", _field, "ReadOnly");
			chkSerialize.DataBindings.Add("Checked", _field, "Serialize");
			chkExclude.DataBindings.Add("Checked", _field, "Exclude");
			chkAutogenerated.DataBindings.Add("Checked", _field, "Autogenerated");
			chkDBReadOnly.DataBindings.Add("Checked", _field, "DBReadOnly");
			txtType.DataBindings.Add("Text", _field, "Type");
			txtVBType.DataBindings.Add("Text", _field, "VBType");
			txtDBType.DataBindings.Add("Text", _field, "DBType");
			txtDBSize.DataBindings.Add("Text", _field, "DBSize");
			txtDBPrecision.DataBindings.Add("Text", _field, "DBPrecision");

			this.Enabled = true;
		}
		#endregion DoBinding
		
		#region SelectedObject
		public object SelectedObject {
			get {
				return _field;
			}
			set {
				_field = (EntityField)value;
				DoBinding();
			}
		}
		#endregion SelectedObject
		
		#region IsDirty
		public bool IsDirty {
			get {
				return false;
			}
		}
		#endregion IsDirty
		
		#region Icon
		public Icon Icon {
			get {
				return Images.CreateIcon(Images.Details);
			}
		}
		#endregion Icon
		
		#region ToString
		public override string ToString() {
			if (_field == null) {
				return "Field: <no field selected>";
			}
			else {
				return "Entity: " + _field.Entity.Name + " | Field: " + _field.Name;
			}
		}
		#endregion ToString
		
		#region CommitChanges
		public bool CommitChanges() {
			return true;
		}
		#endregion CommitChanges
		
		#region QueryUnload
		public void QueryUnload(out bool cancel) {
			if (!this.Validate()) {
				DialogResult res = MessageBox.Show("There are one or more errors with the data on this form. Would you like to close it anyway?", "Validation Error", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);
				if (res == DialogResult.Yes) {
					cancel = false;
				}
				else {
					cancel = true;
				}
			}
			else {
				CommitChanges();
				cancel = false;
			}
		}
		#endregion QueryUnload

		#endregion IObjectEditor implementation
		
		#region Events
		private void ORIndexEditor_Load(object sender, System.EventArgs e) {
			if (_field != null) {
				DoBinding();
			}
		}
		#endregion Events

	}
}